### ISSUE TITLE
 [rt.cpan.org #15595]

### ISSUE THREAD

**Issue by toddr** [toddr/Tie-File#10]
Migrated from [rt.cpan.org#15595](https://rt.cpan.org/Ticket/Display.html?id=15595) (status was 'open')

Requestors:
* SREZIC@cpan.org

From srezic@cpan.org on 2005-11-07 13:18:32
:
```
As Tie::File is a perl core module (according to Module::CoreList since
perl version 5.007003), the Makefile.PL should have a line

     INSTALLDIRS         => $] >= 5.007003 ? 'perl' : 'site',

so Tie::File gets installed in the right place. For a reference, see the
Makefile.PL of Storable.

And while writing this bugreport, just another very minor nit: in line 169
there's some dead code
  my $fh = $self->{FH};
$fh is never used, and FH (upper case) is wrong anyway.

Regards,
    Slaven


```

From toddr@cpan.org on 2013-03-28 05:48:00
:
```
This has been resolved for a while best I can tell
```

From srezic@cpan.org on 2013-04-02 20:35:01
:
```
On 2013-03-28 01:48:00, TODDR wrote:
> This has been resolved for a while best I can tell

Well, this line looks dubious:
https://github.com/toddr/Tie-File/blob/master/Makefile.PL#L14
The condition can never be true.

Regards,
    Slaven

```

From mauke@cpan.org on 2016-01-04 16:45:26
:
```
On Tue Apr 02 16:35:01 2013, SREZIC wrote:
> On 2013-03-28 01:48:00, TODDR wrote:
> > This has been resolved for a while best I can tell
> 
> Well, this line looks dubious:
> https://github.com/toddr/Tie-File/blob/master/Makefile.PL#L14
> The condition can never be true.

We just rediscovered this issue on freenode/#perl. It's still broken.

```

**Comment by toddr** [comment]
@slaven, I get what you're trying to do here with using perl above 5.7, but If this is being installed from CPAN, IMO it should go into site, not perl. The only exception would be between 5.8 and 5.11 where the` @\INC order got messed up.

Sorry for the long delay in response but I'd like to follow this up.

**Comment by toddr** [comment]
@eserte I get what you're trying to do here with using perl above 5.7, but If this is being installed from CPAN, IMO it should go into site, not perl. The only exception would be between 5.8 and 5.11 where the` @\INC order got messed up.

Sorry for the long delay in response but I'd like to follow this up.

**Comment by eserte** [comment]
Nowadays the INSTALLDIRS line should probably look like this:
https://metacpan.org/source/XSAWYERX/Storable-3.15/Makefile.PL#L28
