### ISSUE TITLE
Newest CPAN version would downgrade installed Tie::File version

### ISSUE THREAD

**Issue by eserte** [toddr/Tie-File#12]
Just noticed that CPAN.pm refuses to build+test the recent CPAN release of Tie::File because of a possible downgrade:
```
Testing/Installation stopped: allow_installing_module_downgrades: TODDR/Tie-File-1.01.tar.gz (called for T/TO/TODDR/Tie-File-1.01.tar.gz) contains downgrading module(s) (e.g. 'Tie/File.pm' would downgrade installed '1.02' to '1.01')
```
According to `corelist` Tie::File 1.02 was released with perl v5.23.9.

**Comment by toddr** [comment]
I really don't know how this happened. I thought I was pulling from blead. 1.03 is on its way.
